### ISSUE TITLE
Failing chunk flush and duplicate records sent to Elasticsearch

### ISSUE THREAD

**Issue by maggiedeuitch** [aws/aws-for-fluent-bit#150]
We are using aws-for-fluent-bit with Firehose that sends our logs to Elasticsearch. What we have noticed is there is an unusually high number of duplicate records (there has been an instance of 12k of the same log) being sent. We aren't sure if this is happening because of a communication error between Fluent Bit and Firehose, resulting in the duplicates or something else with the configurations.

Example error messages:
```
[2021/02/17 00:28:11] [ warn] [engine] failed to flush chunk '1-1613521686.952169127.flb', retry in 6 seconds: task_id=2, input=forward.0 > output=firehose.1
[2021/02/17 00:28:12] [ warn] [engine] chunk '1-1613521677.443721002.flb' cannot be retried: task_id=0, input=forward.0 > output=firehose.1
[2021/02/17 00:28:13] [ warn] [engine] chunk '1-1613521681.952523526.flb' cannot be retried: task_id=1, input=forward.0 > output=firehose.1
```

fluent-bit.conf
```
[SERVICE]
    Flush 5
    Parsers_File parsers.conf

[INPUT]
    Name forward
    unix_path /var/run/fluent.sock

# parsers are configured in parsers.conf
[FILTER]
    Name parser
    Match *
    Parser PM2_logs
    Key_Name log
    Preserve_Key On
    Reserve_Data On

[FILTER]
    Name parser
    Match *
    Parser PM2_logs_2
    Key_Name log
    Preserve_Key On
    Reserve_Data On

[FILTER]
    Name parser
    Match *
    Parser environment_service
    Key_Name container_name
    Preserve_Key On
    Reserve_Data On

[OUTPUT]
    Name firehose
    Match logs*
    delivery_stream ${ELASTICSEARCH_DOMAIN}
    region ca-central-1
    role_arn arn:aws:iam::${ELASTICSEARCH_ACCOUNT}:role/ecs-task-firehose-cross-account-role
    time_key  time
    time_key_format %Y-%m-%dT%H:%M:%S%z
```

**Comment by DrewZhang13** [comment]
Hi @maggiedeuitch, I wonder which image version of aws-for-fluent-bit you are using? Does this happen only recently or for a while?

**Comment by maggiedeuitch** [comment]
Hi @DrewZhang13, we are pulling the latest version, last build last week. 
It happened only recently, from February 12th we noticed a spike and throttling. We had done some performance testing, but nothing that would generate 45 million records in such a short time. We also removed fluent bit from the service and tried to recreate the issue checking docker logs, but nothing to indicate duplicates. So we are thinking it's from some interaction with fluent bit and firehose.
<img width="1184" alt="Screen Shot 2021-02-18 at 9 19 32 AM" src="https://user-images.githubusercontent.com/39973013/108377273-de808400-71d1-11eb-8a52-59d0653645bd.png">

**Comment by PettitWesley** [comment]
> [2021/02/17 00:28:11] [ warn] [engine] failed to flush chunk '1-1613521686.952169127.flb', retry in 6 seconds: task_id=2, input=forward.0 > output=firehose.1

Are there other error messages? There must be some other message that explains why it failed to send in the first place

**Comment by maggiedeuitch** [comment]
Sorry, I missed some. There are Firehose messages that say throughput limits may be exceeded, but from the monitoring, it doesn't look like any limits were reached?

```
[2021/02/16 19:40:28] [ warn] [engine] chunk '1-1613504413.30771745.flb' cannot be retried: task_id=0, input=forward.0 > output=firehose.0
time="2021-02-16T19:40:36Z" level=warning msg="[firehose 0] 268 records failed to be delivered. Will retry.\n"
time="2021-02-16T19:40:36Z" level=warning msg="[firehose 0] Throughput limits for the delivery stream may have been exceeded."
```

**Comment by PettitWesley** [comment]
@maggiedeuitch That probably partly explains the duplicates.

This is my guess for what is happening:

1. From time to time you have a spike in log generation from your app(s)
2. That makes you go over Firehose limits occasionally. 
3. Firehose is a weird API because data submission can return partial success- which you can see in that error output. So you can submit 500 records and 200 can fail.
4. Fluent Bit will try to do an immediate retry on just the 200 that failed, but if that fails, the plugin falls back to a full retry of the entire batch. (Plugins are sent records in batches from Fluent Bit core every flush interval, and the batch may require multiple API requests to send).
5. The retry succeeds most of the time probably. This means you successfully sent those 200 failed records, but you also re-submitted all the other records from the batch/flush. 
6. The result is that you see duplicated records in the destination.

That's my hypothesis. Can you please try to increase your Firehose limits? You can also put a Kinesis Stream in front of Kinesis Firehose and use that to scale both of them, using the kinesis shard API.

Also, you should consider switching to the `kinesis_firehose` plugin as it has lower resource usage than the old `firehose` plugin.

**Comment by PettitWesley** [comment]
https://docs.fluentbit.io/manual/pipeline/outputs/firehose

**Comment by maggiedeuitch** [comment]
Thank you for the response. I shall try your suggestions.
