### ISSUE TITLE
Cloudwatch logstream Fluentd migration to fluentbit - Question on best practices

### ISSUE THREAD

**Issue by goatmale** [aws/aws-for-fluent-bit#202]
Previously we were collecting system kubelet, kernel and docker logs with fluentd and now we're migrating to fluentbit.

In the past we have had issues using multiple hosts writing to a single log stream and we would receive errors about out of order logs. 

Is the best practice still to create a seperate log stream for each host?

I don't see this documented anywhere, but it would be helpful to know!

Thank you

**Comment by hossain-rayhan** [comment]
Hi @goatmale , 
>In the past we have had issues using multiple hosts writing to a single log stream and we would receive errors about out of order logs.

Did you try with `FluentBit`?

**Comment by goatmale** [comment]
Hello Hossain - I am test right now in a lower environment and it seems to be working, however I wanted to clarify this before we moved to production.

**Comment by hossain-rayhan** [comment]
Cool. It sould be fine but I would ask @PettitWesley to confirm.

**Comment by PettitWesley** [comment]
It is definitely a best practice to have separate log streams per host. Each Fluent Bit/Fluentd agent should be writing to a single log stream, because of the sequence token requirement in the CW Logs API. That basically requires that only a single agent can write to each log stream.

For best practices using Fluent Bit in EKS see:
- https://aws.amazon.com/blogs/containers/kubernetes-logging-powered-by-aws-for-fluent-bit/
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html
- https://aws.amazon.com/blogs/containers/fluent-bit-integration-in-cloudwatch-container-insights-for-eks/

**Comment by PettitWesley** [comment]
Two of those blogs include configs to collect kubelet, docker, system. and pod logs

**Comment by goatmale** [comment]
Thank you! This is very helpful in confirming how the CW Logs API works and why this was a requirement previously.
