### ISSUE TITLE
multiline parser breaks after while (on log rotation probably)

### ISSUE THREAD

**Issue by tlamr** [aws/aws-for-fluent-bit#228]
Dear maintainers,

  we are using EKS 1.19 with bottle rocket (hence cri-o) and we face this issue https://github.com/fluent/fluent-bit/issues/3886 with multiline parser which brokes the whole log collecting process.
Would you know if and when the resolution might be available In aws-for-fluent-bit?

Thank you,
Tomas

**Comment by zhonghui12** [comment]
Hi @tlamr, we do notice this issue and reported it to our upstream. This problem should be fixed in our upstream - Fluent Bit and then we could involve the solution in aws-for-fluent-bit. However, we will actively work on the solution with our upstream to make sure it could be fixed ASAP. Thanks for your patience. 

In the meantime, could you please try our previous versions? We support multiline after 2.18.0 so version < 2.18.0 might work on your side.

**Comment by PettitWesley** [comment]
This has been fixed in our latest release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.21.1
