### ISSUE TITLE
Make it work on EKS Fargate

### ISSUE THREAD

**Issue by eduardomourar** [aws/aws-for-fluent-bit#48]
We have been able to successfully deploy the fluent bit agent as a sidecar container using the configuration here: https://github.com/aws/containers-roadmap/issues/701#issuecomment-629071376

But one of the main limitations with Fargate is storage. Is there any way to handle purging with this fluent bit agent? Otherwise our log files will easily reach the 20GB limit.

**Comment by hencrice** [comment]
Hey @eduardomourar thanks for reaching out.

Could you elaborate on what you meant by "purging"? From reading the issue you linked, I assume you were asking whether fluent bit supports removing log files it tails. I think it was [discussed](https://github.com/fluent/fluent-bit/issues/215) but not implemented. You probably need to combine things like logrotate with a log routing solution such as Fluent bit

**Comment by eduardomourar** [comment]
Yes, that is precisely what I meant. Being able to remove the log files (or entries) Fluent Bit is tailing. This is more of a feature request being specific to AWS EKS (with Fargate only compute where you have limited storage capacity and there is no EFS support).

Just like the issue you reference from upstream Fluent bit, we believe it makes sense to be part of the log routing. For our case, we only have a single file for logging in each pod so it will be complex to rotate if Fluent Bit is still pending to upload to CloudWatch.

**Comment by hencrice** [comment]
I see. Is it possible to change the way log files are generated (for example by using logrotate) so that older logs will be rotated (to a different name), possibly compressed and finally purged? In the mean time, fluent bit will be configured to tail only the newest log file.

I agree in general it's quite hard to coordinate 2 processes (i.e. log producer and log consumer, which is fluent bit) through file system. But reducing the frequency of rotation, possibly by increasing the size of each rotated log file, generally helps.

Are you ok with commenting on the upstream issue regarding your use cases since this kind of feature request needs community consensus?

**Comment by hencrice** [comment]
Resolving due to lack of activity and we also mentioned it in an upstream issue, where the community generally uses to discuss common fluent bit features. Feel free to reopen if needed.
