### ISSUE TITLE
Container receives SIGSEGV

### ISSUE THREAD

**Issue by sennav** [aws/aws-for-fluent-bit#63]
Hi, for the past few weeks we noticed our services on ECS were going down for no apparent reason. After some investigation we discovered that the latest image of aws-for-fluent-bit is receiving a SIGSEGV signal indicating segmentation fault, see screenshot.

![Screenshot 2020-07-30 at 09 35 23](https://user-images.githubusercontent.com/4136900/88895790-3b721800-d249-11ea-982a-8434f2eddd8a.png)

I don't have any steps to reproduce but it might be network related, if we change the router to use CloudWatch instead of Datadog it doesn't fail (at least we couldn't observe any failure since we deployed 3 days ago). With this hypothesis I'm assuming that there are more network errors when sending data to Datadog than to CloudWatch.

We decided to rollback to 2.3.1 in production and it works normally. I'm not sure if this is of any use for debugging purposes but let me know which info you would need to fix the issue. Thanks!

**Comment by PettitWesley** [comment]
@sennav 

>  for the past few weeks we noticed our services on ECS were going down for no apparent reason. 

One small thing to note, we recently made a change so that the FireLens container does not have to be essential. This means that if it goes down and is non-essential, your whole task will not die. (Unfortunately, the container will not restart, ECS needs that feature). Obviously, if the FireLens container goes down, you would want to alarm on that.

This looks like its the same as https://github.com/fluent/fluent-bit/issues/2387

**Comment by dotanrs** [comment]
@sennav Did the rollback work for you? I tried it as well but kept getting errors

**Comment by PettitWesley** [comment]
@dotanrs Check out recent comments on the core issue; let's discuss there since this isn't really an AWS issue, its core code in fluent bit.

**Comment by PettitWesley** [comment]
Sorry, just realized you were the one who posted there this morning; apologies.

**Comment by hencrice** [comment]
Closing to dedup issues.
