### ISSUE TITLE
Support s3 output

### ISSUE THREAD

**Issue by somdoron** [aws/aws-for-fluent-bit#89]
Fluentbit version 1.6 adds support for s3:

https://docs.fluentbit.io/manual/pipeline/outputs/s3

Please consider adding it.

**Comment by PettitWesley** [comment]
@somdoron We have: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.8.0

**Comment by somdoron** [comment]
Thanks! I guess the chart is not yet published.

**Comment by PettitWesley** [comment]
@somdoron You mean helm chart? 

(If you'd be willing to add that to the fluent bit k8s example repos... please do, we'd appreciate it, @ me and I will review).

**Comment by somdoron** [comment]
@PettitWesley yes, the helm chart at https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit.

Yes, I can add an example, I'm just not sure which repos, can you add links?

**Comment by somdoron** [comment]
I can also try and add the s3 output to the helm chart (and update the version?)

**Comment by PettitWesley** [comment]
@somdoron 

> I can also try and add the s3 output to the helm chart (and update the version?)

👍

Much appreciated

>  I'm just not sure which repos, can you add links?

Ha ha me too lol... that's why I was purposefully vague, I was hoping you were looking at a specific repo. This one looks right: https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit

Let me ping some folks I know and see if there is anything else...
